### ISSUE TITLE
Error with Loot variable for some reason that need a fix!

### ISSUE THREAD

**Issue by gustavohmsilva** [gustavohmsilva/Eternal-Munchkin#1]
Sometimes I get this error during the fight process.

Traceback (most recent call last):
  File "EternalMunchkin.py", line 34, in <module>
    battleOfTheHero()
  File "EternalMunchkin.py", line 14, in battleOfTheHero
    loot = loot - random.randint(1, 3)
UnboundLocalError: local variable 'loot' referenced before assignment

**Comment by darkf** [comment]
Like it tells you right there, you didn't define loot (i.e. assign to it) before that line. Initialize it with something first

**Comment by gustavohmsilva** [comment]
How can I do that? Just add a loot = 0 before everything? I have the feeling that this may be a little more complex than that. This error come from a def xx(): in the code.
